name: core-ts-type CI
on:
  push:
    branches: [main]
    paths:
      - "packages/core-ts-type/**"
      - ".github/workflows/core-ts-type.yml"
  pull_request:
    branches: [main]
    paths:
      - "packages/core-ts-type/**"
      - ".github/workflows/core-ts-type.yml"

jobs:
  module-flow:
    uses: ./.github/workflows/module.yml
    with:
      package-path: packages/core-ts-type
