name: core-ts-type CI
on:
  push:
    branches: [main]
    paths:
      - 'packages/core-ts-type/**'
  pull_request:
    branches: [main]
    paths:
      - 'packages/core-ts-type/**'
env:
  # Setting an environment variable with the value of a configuration variable
  PUBLISH_BRANCH: 'refs/heads/main'
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  PACKAGE_NAME: 'unknown'
  PACKAGE_VERSION: 'unknown'
  NPM: 'pnpm'
  NPM_VERSION: 'unknown'
  HAVE_VALIDATE_SCRIPT: true
  HAVE_LINT_SCRIPT: true
  HAVE_UNIT_TEST_SCRIPT: true

jobs:
  build:
    runs-on: ubuntu-latest
    if: false  # Temporarily disabled
    steps:
      - uses: dcarbone/install-jq-action@v2
      - uses: actions/checkout@v4

      - name: Identify project environment variables
        working-directory: packages/core-ts-type
        run: |
          echo "PACKAGE_NAME=$(cat package.json | jq -r .name)" | tee -a $GITHUB_ENV
          echo "PACKAGE_VERSION=$(cat package.json | jq -r .version)" | tee -a $GITHUB_ENV

      - uses: pnpm/action-setup@v4
        if: env.NPM == 'pnpm'

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'

      - name: Get current npmjs version for ${{env.PACKAGE_NAME}}
        run: |
          echo "NPM_VERSION=$(curl -s https://registry.npmjs.org/${{ env.PACKAGE_NAME }} | jq -r '."dist-tags".latest')" >> $GITHUB_ENV

      - name: Install all workspace dependencies
        run: ${{ env.NPM }} install

      - name: Build all
        run: ${{ env.NPM }} run build

      - name: Validate all
        if: env.HAVE_VALIDATE_SCRIPT == 'true'
        run: ${{ env.NPM }} run validate

      - name: Run unit tests
        if: env.HAVE_UNIT_TEST_SCRIPT == 'true'
        run: ${{ env.NPM }} test

      - name: Run linter checks
        if: env.HAVE_LINT_SCRIPT == 'true'
        run: ${{ env.NPM }} run lint

      # npm publish when PR done
      - name: Publish ${{env.PACKAGE_NAME}} ${{env.PACKAGE_VERSION}}
        working-directory: packages/core-ts-type
        run: ${{ env.NPM }} publish --no-git-checks --access public
        if: |
          github.ref == env.PUBLISH_BRANCH &&
          env.NPM_TOKEN != '' &&
          env.PACKAGE_VERSION != env.NPM_VERSION
        env:
          NODE_AUTH_TOKEN: ${{ env.NPM_TOKEN }}